name: 'Synchronize changes to cloud'
description: 'Synchronize changes to cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
  from-dir:
    description: 'Path to the current repository directory'
    required: true
  to-dir:
    description: 'Path to the sync repository directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ${{ inputs.to-dir }}
      shell: powershell
      
      #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ inputs.from-dir }}/**/appsettings.json'
      env:
        Umbraco.CMS.RuntimeMinification.version: ${{github.run_number}}
        
    - name: Run KuduSync.Net
      run: C:\.\DeploymentScripts\RunKuduSyncNet.ps1 "${{ inputs.from-dir }}" "${{ inputs.to-dir }}" "${{ env.TO_CLOUD_KUDUSYNC_IGNORE }}" "${{github.run_number}}"
      shell: powershell
      
    - name: Create wwwroot .gitignore
      run: |
        New-Item -Path ${{ inputs.to-dir }}${{ env.WWWROOT_PATH }} -Name ".gitignore" -Value "${{ env.WWWROOT_GITIGNORE_RULES }}" -Force
      shell: powershell
      
    - name: Copy Assets (if exists)
      run: | 
        if (Test-Path "${{ env.app-path }}/wwwroot/assets") {
            $dst = Get-ChildItem "${{ inputs.to-dir }}/*/wwwroot"
            Select-Object -First 1 -Expand FullName     
            Copy-Item -Path "${{ env.app-path }}/wwwroot/assets" -Destination "$($dst)" -recurse -Force
        }
      shell: powershell
      
    - name: Commit and push to Cloud
      run: |
            cd ${{ inputs.to-dir }}
            C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell
