name: 'Synchronize changes to cloud'
description: 'Synchronize changes to cloud'
inputs:
  cloud-repository-url:
    description: 'Url of the cloud repository to sync'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install kudusync
      run: npm install -g kudusync
      shell: powershell
    - name: Clone cloud repo
      run: git clone ${{ inputs.cloud-repository-url}} ..\cloud-repository
      shell: powershell
    - name: Create artifact for cloud
      run: |
            md -Force ..\cloud-artifact
            Copy-Item .\.git ..\cloud-artifact
            Copy-Item .\.git\* ..\cloud-artifact\.git -force -recurse
            Copy-Item .\*.web\* ..\cloud-artifact -force -recurse
            Copy-Item .\*.site\* ..\cloud-artifact -force -recurse
      shell: powershell
    - name: Kudusync
      run: kudusync --fromDir ..\cloud-artifact --toDir ..\cloud-repository --ignore ".git;.github;nuget.config" --nextManifest ../kudusyncmanifest.txt --ignoreManifest
      shell: powershell
    - name: Commit and push to Cloud
      run: |
            cd ..\cloud-repository
            C:\.\DeploymentScripts\CommitAndPushToCloud.ps1 "${{github.run_number}}"
      shell: powershell